#!/bin/sh

if [ -n "${CROSS_TRIPLE}" ]; then
	if [ "${CROSS_TRIPLE#*$apple-darwin}" != "${CROSS_TRIPLE}" ]; then
		export CROSS_ROOT="${MACOSX_PATH}/osxcross/target"
		export PATH="${CROSS_ROOT}/bin:${PATH}"
		if [ "${CROSS_TRIPLE}" = "i386-apple-darwin" ]; then
			export CC=o32-clang
			export CXX=o32-clang++
		elif [ "${CROSS_TRIPLE}" = "x86_64-apple-darwin" ]; then
			export CC=o64-clang
			export CXX=o64-clang++
		else
			echo "No such cross toolchain: '${CROSS_TRIPLE}'"
			exit 1
		fi
	else
		if [ ! -d "/usr/${CROSS_TRIPLE}/bin" ]; then
			echo "No such cross toolchain: '${CROSS_TRIPLE}'"
			exit 1
	fi
		export CROSS_ROOT="/usr/${CROSS_TRIPLE}"
		export LD_LIBRARY_PATH="/usr/x86_64-linux-gnu/${CROSS_TRIPLE}/lib:${LD_LIBRARY_PATH}"
		export PATH="${CROSS_ROOT}/bin:${PATH}"
	fi
fi

exec $@
