#!/bin/sh

if [ -z "${CROSS_TRIPLE}" ]; then
    exec $@
    exit $?
fi

case "${CROSS_TRIPLE}" in
    *-apple-darwin)
	export CROSS_ROOT="${MACOSX_PATH}/osxcross/target"
	export PATH="${CROSS_ROOT}/bin:${PATH}"
	case "${CROSS_TRIPLE}" in
	    i386-apple-darwin)
		export CC=o32-clang
		export CXX=o32-clang++
		;;
	    x86_64-apple-darwin)
		export CC=o64-clang
		export CXX=o64-clang++
		;;
	    *)
		echo "No such cross toolchain: '${CROSS_TRIPLE}'"
		exit 1
		;;
	esac
	;;
    *-linux-gnu)
	export CROSS_ROOT="/usr/${CROSS_TRIPLE}"
	export LD_LIBRARY_PATH="/usr/x86_64-linux-gnu/${CROSS_TRIPLE}/lib:${LD_LIBRARY_PATH}"
	export PATH="${CROSS_ROOT}/bin:${PATH}"
	;;
esac

exec $@
